// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNonPJtqjZicd0bvMSihmJTnJbKeKBQ3Q',
    appId: '1:542677479608:web:c8bef891715d453933844d',
    messagingSenderId: '542677479608',
    projectId: 'connectcall-ceee5',
    authDomain: 'connectcall-ceee5.firebaseapp.com',
    storageBucket: 'connectcall-ceee5.firebasestorage.app',
    measurementId: 'G-6C980175W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcHQD7VeztiowevsrczlEZwDgNR8aQoh8',
    appId: '1:542677479608:android:3b72a18f66cb32aa33844d',
    messagingSenderId: '542677479608',
    projectId: 'connectcall-ceee5',
    storageBucket: 'connectcall-ceee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHa8gOnxmhJtO56uJ1urG-TqeD0zILH1U',
    appId: '1:542677479608:ios:aaacddd22db33e0733844d',
    messagingSenderId: '542677479608',
    projectId: 'connectcall-ceee5',
    storageBucket: 'connectcall-ceee5.firebasestorage.app',
    iosBundleId: 'com.example.connectcall',
  );
}
